GET http://localhost:3000/2a71025e
###

POST http://localhost:3000/api/v1/shortener
Content-Type: application/json

{
  "query": "mutation {\n  shortenUrl(originalUrl: \"https://example.com\")\n}\n"
}
###

POST http://localhost:3000/api/v1/shortener
Content-Type: application/json

{
  "query": "query {\n  getOriginalUrl(shortCode: \"0000000003\")\n}\n"
}
###
