
GET http://localhost:3000/000mAUuJNjou
###

POST http://localhost:3000/api/v1/shortener
Content-Type: application/json

{
  "query": "mutation {\n  shortenUrl(originalUrl: \"https://stackoverflow.com\")\n}\n"
}
###

POST http://localhost:3000/api/v1/shortener
Content-Type: application/json

{
  "query": "query {\n  getOriginalUrl(shortCode: \"000mAUuJNjou\")\n}\n"
}
###
